### PR TITLE
Add ref forwarding

### PR DESCRIPTION
**Pull request by aweebit**
I want my `<SlideDown />` component to collapse when user clicks anywhere outside the component. I need a ref to check whether `event.target` is part of it. Sure, I could add another `<div />`, but why not make use of the new `React.forwardRef()` method?

### CODE REVIEW

**Comment by frankwallis** [comment]
This is awesome, thank you! I'm waiting on an upstream release to provide support for the new lifecycle methods in 16.3. Is 16.3 needed for forwardRefs and is the any polyfill to support lower versions?

**Comment by aweebit** [comment]
Yes, 16.3 is required for `React.forwardRef()` to work, but you're already using `getSnapshotBeforeUpdate()` in your code which is also only available starting at 16.3. There is [a polyfill](https://github.com/soupaJ/create-react-ref) however.

**Comment by frankwallis** [comment]
Thanks, so my plan is to add the polyfill and do a minor version release when https://github.com/reactjs/react-transition-group/pull/355 is published, and then merge this and do a major version release.

**Comment by frankwallis** [comment]
Released in 2.0.0, thank you!

**Pull request merged**
